### ISSUE TITLE
sql_fmt needs version bump

### ISSUE THREAD

**Issue by ccavolt** [akoutmos/ecto_dbg#10]
I'm using sql_fmt for formatting SQL in my migrations, which requires version 0.2.0. The current version of ecto_dbg asks for version 0.1.0, which makes dependency resolution fail, so I can't use both sql_fmt and ecto_dbg at the same time in my application.

**Comment by akoutmos** [comment]
Thanks for the heads up! `0.5.0` has just been published to Hex!
