### ISSUE TITLE
Function clause error when logging union query

### ISSUE THREAD

**Issue by ding-an-sich** [akoutmos/ecto_dbg#4]
** (FunctionClauseError) no function clause matching in String.split/3

     The following arguments were given to String.split/3:
     
         # 1
         {:error, "pg_format exited with status code 65280\nUncaught exception: Use of uninitialized value in pattern match (m//) at (...)/deps/ecto_dbg/priv/lib/pgFormatter/Beautify.pm line 965, <STDIN> line 1.\n at (...)/_build/test/lib/ecto_dbg/priv/pg_format line 19, <STDIN> line 1.\n\tmain::__ANON__(\"Use of uninitialized value in pattern match (m//) at (...) called at (...)/deps/ecto_dbg/priv/lib/pgFormatter/Beautify.pm line 965\n\tpgFormatter::Beautify::beautify(pgFormatter::Beautify=HASH(0x56106f996638)) called at (...)/deps/ecto_dbg/priv/lib/pgFormatter/CLI.pm line 170\n\tpgFormatter::CLI::beautify(pgFormatter::CLI=HASH(0x56106f748548)) called at (...)/deps/ecto_dbg/priv/lib/pgFormatter/CLI.pm line 78\n\tpgFormatter::CLI::run(pgFormatter::CLI=HASH(0x56106f748548)) called at (...)/_build/test/lib/ecto_dbg/priv/pg_format line 49"}
     
         # 2
         "\n"
     
         # 3
         []

The error occurs when I'm trying to log a query with multiple union_all. Not sure what's going on.

**Comment by akoutmos** [comment]
This should be fixed in version `0.3.0`!
