### ISSUE TITLE
Switch to Rustler Precompiled

### ISSUE THREAD

**Issue by akoutmos** [akoutmos/ecto_dbg#9]
Leverage https://github.com/philss/rustler_precompiled to remove build step

**Comment by arnodirlam** [comment]
I'm currently getting this error when trying to compile `ecto_dbg` in a Livebook:

```
==> ecto_dbg
Compiling 2 files (.ex)

== Compilation error in file lib/ecto_dbg/sql_formatter.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.17.2) lib/system.ex:1114: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/sql_formatter"])
    (rustler 0.34.0) lib/rustler/compiler/config.ex:76: Rustler.Compiler.Config.metadata!/1
    (rustler 0.34.0) lib/rustler/compiler/config.ex:63: Rustler.Compiler.Config.build/1
    (rustler 0.34.0) lib/rustler/compiler.ex:8: Rustler.Compiler.compile_crate/3
    lib/ecto_dbg/sql_formatter.ex:4: (module)
could not compile dependency :ecto_dbg, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ecto_dbg --force", update it with "mix deps.update ecto_dbg" or clean it with "mix deps.clean ecto_dbg"
```

Would using `rustler_precompiled` solve this issue?

Thanks! ❤️

**Comment by akoutmos** [comment]
Based on the error message, it looks like you don't have rust+cargo installed on your machine. I'll probably work on getting this precompiled some time next week and perhaps even into its own library for wider use :).

**Comment by akoutmos** [comment]
Version `0.4.0` was just released which relies on https://github.com/akoutmos/sql_fmt in order to format the SQL queries. sql_fmt uses `rustler_precompiled` so this shouldn't be all set moving forward!

**Comment by arnodirlam** [comment]
Great, thank you!

I had Rust+Cargo installed, but I had to add the homebrew path to Livebook in `~/.livebookdesktop.sh`. Now that's not needed any more 🎉
